FROM python:3.9.18-alpine3.19
WORKDIR /payment-app
COPY . .
ENV AMQP_USER=roboshop AMQP_PASS=roboshop123
EXPOSE 8080
RUN apk add --no-cache python3-dev build-base linux-headers pcre-dev
RUN pip install -r requirements.txt
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop -h /payment-app
RUN chown -R roboshop:roboshop /payment-app
USER roboshop
CMD ["uwsgi", "--ini", "payment.ini"]